version: "3.7"
services:
  my-mongo-projet:
    image: mongo
    networks: 
        - my-network-projet
    volumes:
        - mongo_data:/data/db

  my-flask-projet:
    build: .
    ports:
      - "5007:5000"
    networks: 
      - my-network-projet
    volumes:
      - ./TEST.txt:/app/TEST.txt
      - ./templates:/app/templates
    depends_on:
      - my-mongo-projet

networks:
  my-network-projet:
    driver: bridge

volumes:
  mongo_data:
